livox_a:
  lidar_driver_node:
    ros__parameters:
      frame_id: livox_a
      sensor_type: livox
      sensor_model: horizon
      host_ip: 192.168.1.100
      sensor_ip: 192.168.1.150
      data_port: 23000 #be sure to assign different ports for each sensor
      imu_port: 24000 #be sure to assign different ports for each sensor
      cmd_port: 25000 #be sure to assign different ports for each sensor
      frequency: 100 #ms
      #echo_mode: single_first # single_
      #coordinate_mode: cartesian # cartesian, spherical
# echo_mode and coordinate_mode must not be implemented in the first beta version of the driver.
