name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble

        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ros:foxy
            ros_distribution: foxy

          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ros:galactic
            ros_distribution: galactic

          # Humble
          - docker_image: ros:humble
            ros_distribution: humble

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 2 # https://github.com/codecov/codecov-action/issues/190#issuecomment-790729633

      - name: run vcs
        run: mkdir $GITHUB_WORKSPACE/src && cd $GITHUB_WORKSPACE && mv `find -maxdepth 1 -not -name . -not -name src` src/$GITHUB_WORKSPACE && vcs import --force --recursive $GITHUB_WORKSPACE/src < build_depends.repo
      - name: Install Dependencies
        run: cd $GITHUB_WORKSPACE && rosdep install --from-paths src --ignore-src -y
      - name: Build
        run: colcon build

