name: documentation
on:
  push:
  pull_request:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: sudo apt update && sudo apt install -y doxygen python3-pip && \
          pip install mkdocs-material \
          mkdocs \
          mkdocs-material \
          Jinja2 \
          ruamel.yaml && \
          pip install git+https://github.com/JakubAndrysek/mkdoxy
      - run: mkdocs gh-deploy --force